### ISSUE TITLE
unrecognized molecules file

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#10]
Dynabench produces 'unrecognized molecules' file which involves HIS residues named differently according to charge and force field. Does it consider them during calculation? The example file attached. 
[Unrecognized_molecules.txt](https://github.com/Atakanzsn/DynaBench/files/14099271/Unrecognized_molecules.txt)

**Comment by ezgikaraca** [comment]
This looks like a FoldX output. If so, this means that these residues will be ignored during energy calculation. The ignored residues correspond to the different protonation states of histidine, which should be named according to https://foldxsuite.crg.eu/allowed-residues for FoldX's recognition. 

On the other hand, checking what interfacea accepts as amino acid abbreviations (https://github.com/Atakanzsn/DynaBench/blob/main/interfacea/interfacea/data.py) made me realize that the submitted histidine nomenclature won't be recognized by interfacea as well.

So, we should think of decent way for making different histidine protonation states counted both at the interfacea and FoldX stages. @Atakanzsn

**Comment by Atakanzsn** [comment]
I'm working on it

**Comment by inantu** [comment]
by the way, not only histidine, but also sulfated residues may be taken into account, later on. For instance, tyrosine sulfation can determine and often enhance protein–protein interaction specificity (DOI:https://doi.org/10.1016/j.jbc.2022.102232).
