### ISSUE TITLE
matplotlib error

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#11]
Different structure from test, the error is below;
ValueError: markevery=[30, 38, 32, 36, 28, 31, 37, 9, 11, 29] is iterable but not a valid numpy fancy index
![image](https://github.com/Atakanzsn/DynaBench/assets/105718558/403ac058-0ca4-4652-accc-563acdf10b62)

**Comment by inantu** [comment]
Chain A = 307, chain B=36

**Comment by Atakanzsn** [comment]
can you check the interface_label_perc.csv file? There should be probably ligand taken as residue with residue number 38 in the chain B? Can you write the which component has residue number 38 in the chain B?

**Comment by inantu** [comment]
VAL   "B	VAL38	3	82"

**Comment by Atakanzsn** [comment]
Can you check your pdb from both file editor and pymol? If your B chain has 36 residues, VAL 38 does not supposed to exist.

**Comment by inantu** [comment]
B chain starts with HIS3.

**Comment by Atakanzsn** [comment]
I just updated the package. this version of the package will not mark the residues it there is any jump in the sequence. I am labelling this issue as feature request. Jumping in the sequence will be fixed in this week
