### ISSUE TITLE
Dynabench juptyer notebook test error

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#15]
While running on Jupyter notebook, (at step 3),  the following error occurs (IndexError: index 0 is out of bounds for axis 0 with size 0). 
<img width="1162" alt="Ekran Resmi 2024-04-09 16 56 48" src="https://github.com/Atakanzsn/DynaBench/assets/105718558/cb4a2287-fed8-4ef4-95e6-f090d6ca4f80">

**Comment by inantu** [comment]
The same error while running on terminal

**Comment by Atakanzsn** [comment]
Can you check the .pdb file? Which OS do you use? I do not encounter with this bug in Windows.

**Comment by inantu** [comment]
3F1P_input.pdb in test folder is empty. By the way I downloaded using git clone. System version is macOS 12.1 (21C52).

**Comment by Atakanzsn** [comment]
I just re-uploaded the test pdb, which seems 56 MB. So, I'm closing the issue for now. If the bug continues, please open the issue again.

**Comment by inantu** [comment]
Pdb file can not be downloaded by using git clone. Ps. I can jump the error by downloading externally.

**Comment by inantu** [comment]
> Pdb file can not be downloaded by using git clone. Ps. I can jump the error by downloading externally.

error encountered only MacOs.

**Comment by inantu** [comment]
at jupyter notebook step 12, calculation related MDanalysis, the following error showed up.

FileNotFoundError: [Errno 2] No such file or directory: '3F1P_dt05_time_ns_stride10_test/tables/interface_label_perc.csv'

**Comment by inantu** [comment]
testing ..stride10.ipynb following error encountered. 

FileNotFoundError: [Errno 2] No such file or directory: '3F1P_dt05_time_ns_stride10_test/3F1P_input_stride10.pdb'

**Comment by Atakanzsn** [comment]
can you give the path of pdb file which in the folder '3F1P_dt05_time_ns_stride10_test'?
