### ISSUE TITLE
An error at Residue Based calculation step

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#16]
At the step which use foldx for the calculations, I encountered the following error.

<img width="1440" alt="Ekran Resmi 2024-04-15 09 25 31" src="https://github.com/Atakanzsn/DynaBench/assets/105718558/ee3aad62-e5e7-40bd-9c1f-390f1dfac148">

**Comment by inantu** [comment]
Now I encounter with the following error
![Uploading Ekran Resmi 2024-04-15 11.52.40.png…]()

**Comment by inantu** [comment]
now I encounter with the following error 
![Uploading Ekran Resmi 2024-04-15 11.55.35.png…]()

**Comment by inantu** [comment]
The following error which I encounter now

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 mol.run_res_based("/Users/nuryoncainan/foldxMacC11_0")

File ~/miniconda3/envs/DynaBench/lib/python3.8/site-packages/DynaBench/Tables.py:225, in dynabench.run_res_based(self, foldx_path)
    223 self.foldx_path = foldx_path
    224 self.rb_flag = True
--> 225 c = self.ResidueBased(self.pdb_file, self.target_path, timestep= self.timestep, timeunit = self.time_unit, time_type=self.time_Type, stride=self.stride, job_path=self.job_path, foldx_path=foldx_path)
    226 c.res_based_tbl()
    227 c.interface_table()

File ~/miniconda3/envs/DynaBench/lib/python3.8/site-packages/DynaBench/Tables.py:439, in dynabench.ResidueBased.__init__(self, pdb_path, target_path, time_type, timestep, timeunit, stride, job_path, foldx_path)
    432 self.rasam_array = freesasa.structureArray(pdb_path,
    433                                            {'separate-chains': True,
    434                                             'separate-models': True})  # rasc, len=402
    435 self.rasac_array = freesasa.structureArray(pdb_path,
    436                                            {'separate-chains': False,
    437                                             'separate-models': True})  # rasm, len=201
--> 439 self.energies = self._res_en(pdb_path, job_path, foldx_path)

File ~/miniconda3/envs/DynaBench/lib/python3.8/site-packages/DynaBench/Tables.py:600, in dynabench.ResidueBased._res_en(inp_file, job_path, foldx_path)
    597 #read outputs
    599 for file in os.listdir(output_path):
--> 600     frame = int(file.split('.')[0].split('_')[-2]) - 1
    601     if frame not in result.keys():
    602         result[frame] = dict()

ValueError: invalid literal for int() with base 10: 'input'


<img width="1440" alt="Ekran Resmi 2024-04-15 12 28 38" src="https://github.com/Atakanzsn/DynaBench/assets/105718558/1109a1d7-4e9e-456f-addb-e53b48a59c66">

**Comment by Atakanzsn** [comment]
can you write the one of the files' name in the folder "models"?
