### ISSUE TITLE
EvoEF.exe error

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#4]
while running the tests file in jupyter notebook, the error encountered is as follows 
![image](https://github.com/Atakanzsn/DynaBench/assets/105718558/d81dce8d-fbf9-4223-b9af-ba3ef8f93721)

**Comment by Atakanzsn** [comment]
You need to manually download the dll file, please follow the instructions in the link: https://windll.com/dll/other/libgcc-s-dw2-1

**Comment by inantu** [comment]
dll file was downloaded, the error in test step is below 
![image](https://github.com/Atakanzsn/DynaBench/assets/105718558/e83b2533-cfe8-414f-8879-78c522053fa5)

**Comment by Atakanzsn** [comment]
Can you check the .dll file? Is it compatible with your computer's bit? Also can you reboot the pc and try again?

**Comment by Atakanzsn** [comment]
Can you try to compile EvoEF to your pc? You can use the following link: https://github.com/tommyhuangthu/EvoEF
