### ISSUE TITLE
RMSF plot error

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#5]
![image](https://github.com/Atakanzsn/DynaBench/assets/105718558/083430df-91e8-4e1b-899c-fc38381c3012)

**Comment by Atakanzsn** [comment]
can you compare the QualityControl-overres.csv files which one in your test folder, while the other one is in the downloaded job folder with the same name except "test"

**Comment by Atakanzsn** [comment]
can you check the interface_label_perc.csv files?

**Comment by Atakanzsn** [comment]
Teh problem caused from EvoEF, I am closing this issue. We can continue from #4
