### ISSUE TITLE
plot_params.json file

### ISSUE THREAD

**Issue by inantu** [Atakanzsn/DynaBench#9]
it produces table_params.json but not plot_params.json. The error as follows 
![image](https://github.com/Atakanzsn/DynaBench/assets/105718558/95bccf4a-f78c-4329-b1a5-73bbcc9cff8a)

**Comment by Atakanzsn** [comment]
can you check the job_name parameters in the table_params.json and plot_params.json files? They must be identical

**Comment by inantu** [comment]
there is not plot_params.json file.

**Comment by Atakanzsn** [comment]
I just updated the package, can you try with this version?
